FROM python:3.9-slim

WORKDIR /acapy

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip
RUN pip install aries-cloudagent aries-askar indy-vdr indy-credx

COPY config.yaml ./config.yaml

CMD ["aca-py", "start", "--arg-file", "./config.yaml", "-it", "http", "0.0.0.0", "3021"]